"""new fields to user model

Revision ID: 238f651df3c4
Revises: ded8e80c7d42
Create Date: 2019-01-07 00:57:04.847824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238f651df3c4'
down_revision = 'ded8e80c7d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
